### ISSUE TITLE
tweaks

### ISSUE THREAD

**Issue by RichMorin** [acook/remedy#14]
There are a number of printable characters that report back as "unknown" (e.g., @, #, $, %, &, *, =, +, <, and >). Might you be interested in having a patch to add these?  Also, what about an option to allow printable characters to pass through without any mapping?

-r

**Comment by acook** [comment]
Definitely interested in patches for bugs! 

I'm not 100% sure what you mean about no mapping, you mean just returning the string value? If there's a simple way to flag it, I don't see why that wouldn't be a useful addition. I was a focused on single keystroke commands and wrappers, but really you could wrap them later too.

**Comment by acook** [comment]
Please let me know if you ended up adding any of those patches, until then I'm going to close this ancient bug, but feel free to open a new one!
