### ISSUE TITLE
Character typo

### ISSUE THREAD

**Issue by mjago** [acook/remedy#8]
Hi
Thanks for gem - found a typo though:
````ruby
        '[' => :left_bracket,
        ']' => :right_bracked,

````

[link](https://github.com/acook/remedy/blob/0f49ace76b8e42ca769cb9591159fcf227c3765e/lib/remedy/characters.rb#L68-L69)

**Comment by acook** [comment]
Thanks for the bug report, fixed in this commit: https://github.com/acook/remedy/commit/b147bbeae11ce94ef43231cbe07a898e7d1cebe5
